/**
 * Role Configurations - Comprehensive definitions for each engineering role
 *
 * This file contains extensive configuration data for five major engineering roles:
 * - Backend & Distributed Systems
 * - Machine Learning & Data
 * - Frontend & Full-Stack
 * - Infrastructure & Platform
 * - Security & Reliability
 *
 * Each configuration includes 15+ items for focus areas, scenarios, and relevant problems
 * to provide rich context for role-specific problem transformations.
 */

import { RoleFamily, RoleConfiguration } from '@/data-types/role';

export const ROLE_CONFIGURATIONS: Record<RoleFamily, RoleConfiguration> = {
  [RoleFamily.BACKEND_SYSTEMS]: {
    title: 'Backend & Distributed Systems Engineer',
    focusAreas: [
      'API design and optimization',
      'Distributed systems architecture',
      'Database performance and optimization',
      'Microservices orchestration',
      'Message queue and event streaming',
      'Caching strategies and invalidation',
      'Load balancing and traffic distribution',
      'Service discovery and registration',
      'Data consistency and ACID properties',
      'Transaction management and isolation',
      'Performance monitoring and profiling',
      'Scalability patterns and sharding',
      'Fault tolerance and circuit breakers',
      'Event-driven architecture design',
      'Distributed consensus algorithms',
    ],
    relevantProblems: [
      'Rate limiting and throttling mechanisms',
      'Distributed caching and cache coherence',
      'Database sharding and partitioning',
      'Event sourcing and CQRS patterns',
      'Saga pattern for distributed transactions',
      'Bulkhead pattern for fault isolation',
      'Distributed locking and leader election',
      'Data replication and synchronization',
      'Message deduplication and ordering',
      'Service mesh and traffic management',
      'Database connection pooling',
      'Distributed system observability',
      'Circuit breaker implementation',
      'Eventual consistency handling',
      'Distributed session management',
    ],
    keyMetrics: ['requests per second', 'p99 latency', 'error rate', 'throughput'],
    typicalScenarios: [
      'Design a distributed rate limiter',
      'Implement multi-level caching system',
      'Build event-driven order processing',
      'Design database sharding strategy',
      'Create distributed session store',
      'Implement saga pattern for payments',
      'Build real-time notification system',
      'Design API gateway with load balancing',
      'Implement distributed locking service',
      'Create event sourcing architecture',
      'Build microservices communication layer',
      'Design distributed job scheduling system',
      'Implement circuit breaker pattern',
      'Create distributed configuration service',
      'Build idempotent API endpoints',
    ],
    algorithmPreferences: ['hashing', 'consistent hashing', 'bloom filters', 'consensus algorithms'],
  },

  [RoleFamily.ML_DATA]: {
    title: 'Machine Learning & Data Engineer',
    focusAreas: [
      'Data pipeline orchestration and scheduling',
      'Feature engineering and selection',
      'Model training and hyperparameter tuning',
      'Model serving and inference optimization',
      'Real-time stream processing',
      'Batch processing and ETL workflows',
      'Data quality monitoring and validation',
      'MLOps and model lifecycle management',
      'A/B testing and experimentation',
      'Data warehousing and lake architecture',
      'Model monitoring and drift detection',
      'Distributed training and scaling',
      'Data lineage and governance',
      'Feature stores and data versioning',
      'ML pipeline automation and CI/CD',
    ],
    relevantProblems: [
      'Real-time feature computation and serving',
      'Data deduplication and entity resolution',
      'Streaming aggregations and windowing',
      'Batch processing optimization',
      'Model deployment and versioning',
      'Feature drift detection and handling',
      'Data validation and anomaly detection',
      'Pipeline orchestration and dependencies',
      'Cold start problems in recommendations',
      'Scalable model training strategies',
      'Data sampling and bias correction',
      'Multi-armed bandit optimization',
      'Distributed model serving',
      'Real-time scoring and ranking',
      'Data catalog and discovery systems',
    ],
    keyMetrics: ['data freshness', 'pipeline latency', 'processing throughput', 'model accuracy'],
    typicalScenarios: [
      'Build real-time recommendation engine',
      'Design streaming ML feature pipeline',
      'Implement A/B testing framework',
      'Create distributed training system',
      'Build fraud detection pipeline',
      'Design data lake architecture',
      'Implement feature store platform',
      'Create model monitoring dashboard',
      'Build real-time personalization system',
      'Design batch processing workflows',
      'Implement data quality monitoring',
      'Create experiment tracking system',
      'Build scalable inference service',
      'Design data versioning system',
      'Implement automated ML pipeline',
    ],
    algorithmPreferences: ['sampling algorithms', 'streaming algorithms', 'probabilistic data structures', 'MapReduce patterns'],
  },

  [RoleFamily.FRONTEND_FULLSTACK]: {
    title: 'Frontend & Full-Stack Engineer',
    focusAreas: [
      'UI performance optimization and Core Web Vitals',
      'State management and data flow',
      'Real-time collaboration and synchronization',
      'Progressive web apps and service workers',
      'API integration and error handling',
      'Accessibility and WCAG compliance',
      'Mobile responsiveness and cross-device UX',
      'SEO optimization and meta tags',
      'Bundle optimization and code splitting',
      'Cross-browser compatibility',
      'Component architecture and reusability',
      'Animation and micro-interactions',
      'Testing strategies and automation',
      'Security and XSS prevention',
      'Micro-frontends and module federation',
    ],
    relevantProblems: [
      'Virtual scrolling and windowing',
      'Debouncing and throttling user inputs',
      'Offline synchronization and conflict resolution',
      'Optimistic UI updates and rollback',
      'Client-side caching and invalidation',
      'Lazy loading and code splitting',
      'Real-time collaborative editing conflicts',
      'Responsive image optimization',
      'Form validation and error handling',
      'Infinite scroll with search/filter',
      'Drag and drop with collision detection',
      'Multi-language internationalization',
      'Theme switching and CSS-in-JS',
      'WebSocket connection management',
      'Progressive enhancement strategies',
    ],
    keyMetrics: ['first contentful paint', 'time to interactive', 'bundle size', 'frame rate'],
    typicalScenarios: [
      'Implement infinite scrolling feed',
      'Build real-time collaborative editor',
      'Create offline-first PWA application',
      'Design responsive dashboard with charts',
      'Build drag-and-drop kanban board',
      'Implement virtual table for large datasets',
      'Create multi-step form wizard',
      'Build real-time chat application',
      'Design accessible component library',
      'Implement advanced search with filters',
      'Create image gallery with lazy loading',
      'Build interactive data visualization',
      'Implement undo/redo functionality',
      'Design micro-frontend architecture',
      'Create performance monitoring dashboard',
    ],
    algorithmPreferences: ['tree diffing', 'memoization', 'virtual DOM algorithms', 'event delegation'],
  },

  [RoleFamily.INFRASTRUCTURE_PLATFORM]: {
    title: 'Infrastructure & Platform Engineer',
    focusAreas: [
      'Container orchestration and Kubernetes',
      'CI/CD pipeline design and optimization',
      'Infrastructure as code and GitOps',
      'Service mesh and traffic management',
      'Observability and monitoring systems',
      'Auto-scaling and capacity planning',
      'Disaster recovery and backup strategies',
      'Network security and firewalls',
      'Cloud cost optimization',
      'Multi-cloud and hybrid deployments',
      'Compliance and security policies',
      'Platform as a Service (PaaS) design',
      'DevOps toolchain integration',
      'Performance tuning and bottleneck analysis',
      'Infrastructure automation and orchestration',
    ],
    relevantProblems: [
      'Resource scheduling and bin packing',
      'Blue-green and canary deployment strategies',
      'Service discovery and load balancing',
      'Configuration management and secrets',
      'Auto-scaling based on metrics',
      'Container image optimization',
      'Network routing and traffic shaping',
      'Log aggregation and analysis',
      'Backup and restore automation',
      'Certificate management and rotation',
      'Infrastructure drift detection',
      'Multi-tenancy and resource isolation',
      'Performance monitoring and alerting',
      'Dependency management in deployments',
      'Infrastructure security hardening',
    ],
    keyMetrics: ['resource utilization', 'deployment frequency', 'MTTR', 'infrastructure cost'],
    typicalScenarios: [
      'Design Kubernetes auto-scaling system',
      'Implement blue-green deployment pipeline',
      'Build service mesh with Istio',
      'Create infrastructure monitoring dashboard',
      'Design disaster recovery automation',
      'Implement GitOps workflow',
      'Build multi-cloud deployment strategy',
      'Create container security scanning',
      'Design cost optimization system',
      'Implement infrastructure compliance checks',
      'Build log aggregation platform',
      'Create automated backup system',
      'Design network segmentation strategy',
      'Implement configuration drift detection',
      'Build platform self-service portal',
    ],
    algorithmPreferences: ['bin packing', 'scheduling algorithms', 'graph algorithms', 'optimization algorithms'],
  },

  [RoleFamily.SECURITY_RELIABILITY]: {
    title: 'Security & Reliability Engineer',
    focusAreas: [
      'Threat detection and analysis',
      'Incident response and forensics',
      'Chaos engineering and resilience testing',
      'Access control and identity management',
      'Compliance automation and auditing',
      'Vulnerability assessment and penetration testing',
      'Security monitoring and SIEM',
      'Encryption and key management',
      'Zero trust architecture implementation',
      'DDoS protection and mitigation',
      'Intrusion detection and prevention',
      'Security awareness and training',
      'Disaster recovery and business continuity',
      'Risk assessment and threat modeling',
      'Security policy enforcement and automation',
    ],
    relevantProblems: [
      'Anomaly detection in network traffic',
      'Rate limiting and DDoS mitigation',
      'Circuit breaker implementation',
      'Audit logging and compliance tracking',
      'Encryption key rotation and management',
      'Multi-factor authentication systems',
      'Fraud detection and prevention',
      'Security event correlation',
      'Access pattern analysis',
      'Vulnerability scanning automation',
      'Incident escalation and notification',
      'Security configuration management',
      'Threat intelligence integration',
      'Behavioral analysis and profiling',
      'Automated security response systems',
    ],
    keyMetrics: ['MTBF', 'detection accuracy', 'false positive rate', 'recovery time'],
    typicalScenarios: [
      'Build real-time fraud detection system',
      'Implement zero trust network architecture',
      'Design incident response automation',
      'Create security monitoring dashboard',
      'Build DDoS protection system',
      'Implement automated vulnerability scanner',
      'Design access control management system',
      'Create security compliance checker',
      'Build threat detection pipeline',
      'Implement chaos engineering platform',
      'Design disaster recovery automation',
      'Create security audit trail system',
      'Build behavioral anomaly detector',
      'Implement security policy engine',
      'Design encrypted communication system',
    ],
    algorithmPreferences: ['pattern matching', 'anomaly detection algorithms', 'cryptographic algorithms', 'statistical analysis'],
  },
};